PhotoCritic/Controllers/OpinionatedIndividualPhotosController.cs
using Microsoft.AspNet.Identity;
using PhotoCritic.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhotoCritic.Controllers
{
    public class OpinionatedIndividualPhotosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: OpinionatedIndividualPhotos
        public ActionResult Index()
        {
            return View();
        }

        // GET: OpinionatedIndividualPhotos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: OpinionatedIndividualPhotos/Create
        public ActionResult LikeCreate([Bind(Include = "Id,PhotoId,OpinionatedIndividualId,LikeDislike,Comment,Reason1,Reason2")] int id)
        {
            OpinionatedIndividualPhoto opinionatedIndividualPhoto = new OpinionatedIndividualPhoto();
            opinionatedIndividualPhoto.LikeDislike = true;
            opinionatedIndividualPhoto.PhotoId = id;
            ViewBag.CommentStatus = db.Photos.Where(x => x.Id == opinionatedIndividualPhoto.PhotoId).Select(x => x.CommentsEnabled).FirstOrDefault();
            ViewBag.CategoryOfPhotoForReasons = db.Photos.Where(x => x.Id == opinionatedIndividualPhoto.PhotoId).Select(x => x.CategoryId).FirstOrDefault().ToString();

            return View(opinionatedIndividualPhoto);
        }

        // POST: OpinionatedIndividualPhotos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LikeCreate([Bind(Include = "Id,PhotoId,OpinionatedIndividualId,LikeDislike,Comment,Reason1,Reason2")] OpinionatedIndividualPhoto opinionatedIndividualPhoto)
        {
            var userResult = User.Identity.GetUserId();
            var currentUser = db.OpinionatedIndividuals.Where(x => userResult == x.ApplicationId).FirstOrDefault();
            opinionatedIndividualPhoto.OpinionatedIndividualId = currentUser.Id;
            var photoInteractedWith = db.Photos.Where(x => x.Id == opinionatedIndividualPhoto.PhotoId).FirstOrDefault();

            if (ModelState.IsValid)
            {
                db.OpinionatedIndividualPhotos.Add(opinionatedIndividualPhoto);
                db.SaveChanges();
                AddInteractionToPhoto(photoInteractedWith, opinionatedIndividualPhoto);
                return RedirectToAction("Index", "OpinionatedIndividuals");
            }

            return View(opinionatedIndividualPhoto);
        }

        // GET: OpinionatedIndividualPhotos/Create
        public ActionResult DislikeCreate([Bind(Include = "Id,PhotoId,OpinionatedIndividualId,LikeDislike,Comment,Reason1,Reason2")] int id)
        {
            OpinionatedIndividualPhoto opinionatedIndividualPhoto = new OpinionatedIndividualPhoto();
            opinionatedIndividualPhoto.LikeDislike = false;
            opinionatedIndividualPhoto.PhotoId = id;
            ViewBag.CommentStatus = db.Photos.Where(x => x.Id == opinionatedIndividualPhoto.PhotoId).Select(x => x.CommentsEnabled).FirstOrDefault();
            ViewBag.CategoryOfPhotoForReasons = db.Photos.Where(x => x.Id == opinionatedIndividualPhoto.PhotoId).Select(x => x.CategoryId).FirstOrDefault().ToString();

            return View(opinionatedIndividualPhoto);
        }

        // POST: OpinionatedIndividualPhotos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DislikeCreate([Bind(Include = "Id,PhotoId,OpinionatedIndividualId,LikeDislike,Comment,Reason1,Reason2")] OpinionatedIndividualPhoto opinionatedIndividualPhoto)
        {
            var userResult = User.Identity.GetUserId();
            var currentUser = db.OpinionatedIndividuals.Where(x => userResult == x.ApplicationId).FirstOrDefault();
            opinionatedIndividualPhoto.OpinionatedIndividualId = currentUser.Id;
            var photoInteractedWith = db.Photos.Where(x => x.Id == opinionatedIndividualPhoto.PhotoId).FirstOrDefault();

            if (ModelState.IsValid)
            {
                db.OpinionatedIndividualPhotos.Add(opinionatedIndividualPhoto);
                db.SaveChanges();
                AddInteractionToPhoto(photoInteractedWith, opinionatedIndividualPhoto);
                return RedirectToAction("Index", "OpinionatedIndividuals");
            }

            return View(opinionatedIndividualPhoto);
        }

        // GET: OpinionatedIndividualPhotos/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OpinionatedIndividualPhotos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public void AddInteractionToPhoto ([Bind(Include = "Id, ApplicationId, ImageName, ImagePath, CategoryId, Hidden, CommentsEnabled, TotalLikes, TotalDislikes, ImageFile, WhenCreated, TotalInteractions")] Photo photoInteractedWith, OpinionatedIndividualPhoto opinionatedIndividualPhoto)
        {
            if (opinionatedIndividualPhoto.LikeDislike == true)
            {
                photoInteractedWith.TotalLikes += 1;
            }
            else if (opinionatedIndividualPhoto.LikeDislike == false)
            {
                photoInteractedWith.TotalDislikes += 1;
            }

            photoInteractedWith.TotalInteractions += 1;

            if (ModelState.IsValid)
            {
                db.Entry(photoInteractedWith).State = EntityState.Modified;
                db.SaveChanges();
            }
        }
    }
}

PhotoCritic/Controllers/OpinionatedIndividualsController.cs
using Microsoft.AspNet.Identity;
using PhotoCritic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;

namespace PhotoCritic.Controllers
{
    public class OpinionatedIndividualsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: OpinionatedIndividuals
        public ActionResult Index(string categorySelection)
        {
            var userResult = User.Identity.GetUserId();
            var categories = db.Categories.Select(x => x.Name);
            ViewBag.categorySelection = new SelectList(categories);

            if (!string.IsNullOrEmpty(categorySelection))
            {
                var photosInCategory = db.Photos.Where(x => x.Category.Name.Contains(categorySelection) && x.Hidden == false && userResult != x.ApplicationId).OrderByDescending(x => x.WhenCreated).ToList();
                return View(photosInCategory);
            }

            var recentImages = db.Photos.Where(x => userResult != x.ApplicationId && x.Hidden == false).OrderByDescending(x => x.WhenCreated).ToList();
            return View(recentImages);
        }

        // GET: OpinionatedIndividuals/Details/5
        public ActionResult Dashboard()
        {
            var userResult = User.Identity.GetUserId();
            var currentUser = db.OpinionatedIndividuals.Include(x => x.Age).Include(x => x.Sex).Include(x => x.Race).Include(x => x.Location).Include(x => x.Education).Include(x => x.Profession).Include(x => x.IncomeLevel).Include(x => x.MaritalStatus).Where(x => userResult == x.ApplicationId).FirstOrDefault();

            var myInteractionCount = db.OpinionatedIndividualPhotos.Where(x => x.OpinionatedIndividualId == currentUser.Id).ToList().Count();
            ViewBag.interactionCount = myInteractionCount;
            var myLikeCount = db.OpinionatedIndividualPhotos.Where(x => x.OpinionatedIndividualId == currentUser.Id && x.LikeDislike == true).ToList().Count();
            var myDislikeCount = db.OpinionatedIndividualPhotos.Where(x => x.OpinionatedIndividualId == currentUser.Id && x.LikeDislike == false).ToList().Count();

            try
            {
                double likeDivision = ((double)myLikeCount / (double)myInteractionCount);
                if (double.IsNaN(likeDivision) == true)
                {
                    throw new DivideByZeroException();
                }
                else
                {
                    double likeResult = likeDivision * 100;
                    var likePercent = Convert.ToInt32(likeResult);
                    ViewBag.percentLike = likePercent;
                }
            }
            catch (DivideByZeroException)
            {
                ViewBag.percentLike = 0;
            }

            try
            {

                var dislikeDivision = ((double)myDislikeCount / (double)myInteractionCount);
                if (double.IsNaN(dislikeDivision) == true)
                {
                    throw new DivideByZeroException();
                }
                else
                {
                    double dislikeResult = dislikeDivision * 100;
                    var dislikePercent = Convert.ToInt32(dislikeResult);
                    ViewBag.percentDislike = dislikePercent;
                }
            }
            catch (DivideByZeroException)
            {
                ViewBag.percentDislike = 0;
            }
            
            try
            {
                var myMostInteractedPhoto = db.Photos.Where(x => userResult == x.ApplicationId).OrderByDescending(x => x.TotalInteractions).FirstOrDefault();
                ViewBag.myMostInteractedImagePath = myMostInteractedPhoto.ImagePath;
            }
            catch (Exception e)
            {
                ViewBag.myMostInteractedImagePath = "None";
            }

            try
            {
                var myMostLikedPhoto = db.Photos.Where(x => userResult == x.ApplicationId).OrderByDescending(x => x.TotalLikes).FirstOrDefault();
                ViewBag.myMostLikedImagePath = myMostLikedPhoto.ImagePath;
            }
            catch (Exception e)
            {
                ViewBag.myMostLikedImagePath = "None";
            }

            try
            {
                var myMostDislikedPhoto = db.Photos.Where(x => userResult == x.ApplicationId).OrderByDescending(x => x.TotalDislikes).FirstOrDefault();
                ViewBag.myMostDislikedImagePath = myMostDislikedPhoto.ImagePath;
            }
            catch (Exception e)
            {
                ViewBag.myMostDislikedImagePath = "None";
            }

            return View(currentUser);
        }

        // GET: OpinionatedIndividuals/Create
        public ActionResult Create()
        {
            var ages = db.Ages.ToList();
            var sexes = db.Sexes.ToList();
            var races = db.Races.ToList();
            var locations = db.Locations.ToList();
            var educations = db.Educations.ToList();
            var professions = db.Professions.ToList();
            var maritalStatuses = db.MaritalStatuses.ToList();
            var incomeLevels = db.IncomeLevels.ToList();

            OpinionatedIndividual opinionatedIndividual = new OpinionatedIndividual()
            {
                Ages = ages,
                Sexes = sexes,
                Races = races,
                Locations = locations,
                Educations = educations,
                Professions = professions,
                MaritalStatuses = maritalStatuses,
                IncomeLevels = incomeLevels
            };
            return View(opinionatedIndividual);
        }

        // POST: OpinionatedIndividuals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AgeId,SexId,RaceId,LocationId,EducationId,ProfessionId,IncomeLevelId,MaritalStatusId,ApplicationId")] OpinionatedIndividual opinionatedIndividual)
        {
            opinionatedIndividual.ApplicationId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.OpinionatedIndividuals.Add(opinionatedIndividual);
                db.SaveChanges();
                return RedirectToAction("Dashboard");
            }

            return View(opinionatedIndividual);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ages = db.Ages.ToList();
            var sexes = db.Sexes.ToList();
            var races = db.Races.ToList();
            var locations = db.Locations.ToList();
            var educations = db.Educations.ToList();
            var professions = db.Professions.ToList();
            var maritalStatuses = db.MaritalStatuses.ToList();
            var incomeLevels = db.IncomeLevels.ToList();

            OpinionatedIndividual opinionatedIndividual = db.OpinionatedIndividuals.Find(id);
            {
                opinionatedIndividual.Ages = ages;
                opinionatedIndividual.Sexes = sexes;
                opinionatedIndividual.Races = races;
                opinionatedIndividual.Locations = locations;
                opinionatedIndividual.Educations = educations;
                opinionatedIndividual.Professions = professions;
                opinionatedIndividual.MaritalStatuses = maritalStatuses;
                opinionatedIndividual.IncomeLevels = incomeLevels;
            };

            if (opinionatedIndividual == null)
            {
                return HttpNotFound();
            }
            return View(opinionatedIndividual);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ApplicationId,AgeId,SexId,RaceId,LocationId,EducationId,ProfessionId,IncomeLevelId,MaritalStatusId")] OpinionatedIndividual opinionatedIndividual)
        {
            if (ModelState.IsValid)
            {
                db.Entry(opinionatedIndividual).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Dashboard");
            }
            return View(opinionatedIndividual);
        }

        public ActionResult CheckIfVoted(int id)
        {
            var userResult = User.Identity.GetUserId();
            var currentOpinionatedIndividualId = db.OpinionatedIndividuals.Where(x => userResult == x.ApplicationId).Select(x => x.Id).FirstOrDefault();
            var voteForPhoto = db.OpinionatedIndividualPhotos.Where(x => currentOpinionatedIndividualId == x.OpinionatedIndividualId && id == x.PhotoId).FirstOrDefault();
            TempData["vote"] = voteForPhoto;

            return null;
        }

    }
}

PhotoCritic/Views/OpinionatedIndividuals/Create.cshtml
@model PhotoCritic.Models.OpinionatedIndividual

@{
    ViewBag.Title = "Create";
}

<h2>My Information</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Please enter your information:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Age, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AgeId, new SelectList(Model.Ages, "Id", "Name"), "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AgeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sex, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SexId, new SelectList(Model.Sexes, "Id", "Name"), "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SexId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Race, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RaceId, new SelectList(Model.Races, "Id", "Name"), "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RaceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LocationId, new SelectList(Model.Locations, "Id", "Name"), "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Education, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EducationId, new SelectList(Model.Educations, "Id", "Name"), "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EducationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profession, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProfessionId, new SelectList(Model.Professions, "Id", "Name"), "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProfessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaritalStatus, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MaritalStatusId, new SelectList(Model.MaritalStatuses, "Id", "Name"), "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaritalStatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IncomeLevel, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IncomeLevelId, new SelectList(Model.IncomeLevels, "Id", "Name"), "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IncomeLevelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhotoCritic/Views/OpinionatedIndividuals/Dashboard.cshtml
@{
    Layout = "~/Views/Shared/_Layout_User.cshtml";
}

@model PhotoCritic.Models.OpinionatedIndividual

@{
    ViewBag.Title = "Dashboard";
}

<h2>Dashboard</h2>

<div class="row">
    <div class="col-lg-8">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">My Info:</h3>
            </div>
            <div class="panel-body">
                <dt>
                    @Html.DisplayNameFor(model => model.Age.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Age.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Sex.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Sex.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Race.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Race.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Location.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Location.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Education.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Education.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Profession.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Profession.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MaritalStatus.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MaritalStatus.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IncomeLevel.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IncomeLevel.Name)
                </dd>
                </dl>
                </br>
                <p>
                    <a href="@Url.Action("Edit", "OpinionatedIndividuals", new { id = Model.Id })" class="btn btn-info">Edit</a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title"># of photos I have interacted with:</h3>
            </div>
            <div class="panel-body">
                @{
                    if (ViewBag.interactionCount == 0)
                    {
                        <h4>You have not interacted with any photos.</h4>
                        <h4>Get voting!</h4>
                    }
                    else
                    {
                        <h1> @ViewBag.interactionCount </h1>
                    }
                }
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">% of likes I have given:</h3>
            </div>
            <div class="panel-body">
                @{
                    if (ViewBag.percentLike == 0)
                    {
                        <h4>You have not liked any photos.</h4>
                        <h4>Harsh!</h4>
                    }
                    else
                    {
                        <h1> @ViewBag.percentLike% </h1>
                    }
                }
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">% of dislikes I have given:</h3>
            </div>
            <div class="panel-body">
                @{
                    if (ViewBag.percentDislike == 0)
                    {
                        <h4>You have not disliked any photos.</h4>
                        <h4>You're too kind!</h4>
                    }
                    else
                    {
                        <h1> @ViewBag.percentDislike% </h1>
                    }
                }
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title">My photo most interacted with:</h3>
            </div>
            <div class="panel-body">
                @{
                    if (ViewBag.myMostInteractedImagePath == "None")
                    {
                        <h4>None of your photos have been interacted with yet.</h4>
                    }
                    else
                    {
                        <img src="@Url.Content(ViewBag.myMostInteractedImagePath)" width="320" />
                    }
                }
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title">My photo with the most likes:</h3>
            </div>
            <div class="panel-body">
                @{
                    if (ViewBag.myMostLikedImagePath == "None")
                    {
                        <h4>None of your photos have been liked yet.</h4>
                    }
                    else
                    {
                        <img src="@Url.Content(ViewBag.myMostLikedImagePath)" width="320" />
                    }
                }
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title">My photo with the most dislikes:</h3>
            </div>
            <div class="panel-body">
                @{
                    if (ViewBag.myMostDislikedImagePath == "None")
                    {
                        <h4>None of your photos have been disliked yet.</h4>
                    }
                    else
                    {
                        <img src="@Url.Content(ViewBag.myMostDislikedImagePath)" width="320" />
                    }
                }
            </div>
        </div>
    </div>
</div>

PhotoCritic/Views/OpinionatedIndividuals/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout_User.cshtml";
}

@model IEnumerable<PhotoCritic.Models.Photo>

@{
    ViewBag.Title = "Index";
}

<h2>Recent Photos</h2>

<p>
    @using (Html.BeginForm())
    {
    <p>
        Filter by Category: @Html.DropDownList("categorySelection", "All")
        <input type="submit" value="Filter" />
    </p>
}
    </p>

<br/>
@{ int i = 0; }
<div class="row">
    
        @foreach(var item in Model)
        {
            if (i > 0 && i % 2 == 0)
            {
                @:</div><div class="row">
            }
            <div class="col-lg-6">
                @Html.Action("CheckIfVoted", "OpinionatedIndividuals", new { id = item.Id })
                <h3>@Html.DisplayFor(modelItem => item.ImageName) </h3>
                <img src="@Url.Content(item.ImagePath)" width="300" /> <br />
                @{
                    if (TempData["vote"] == null)
                    {
                            <a href="@Url.Action("LikeCreate", "OpinionatedIndividualPhotos", new { id = item.Id })" class="btn btn-default"> <img src="~/ProjectImages/Like.png" alt="Like" height="50" /> </a>
                            <a href="@Url.Action("DislikeCreate", "OpinionatedIndividualPhotos", new { id = item.Id })" class="btn btn-default"> <img src="~/ProjectImages/Dislike.png" alt="Dislike" height="50" /> </a>
                    }

                    if (TempData["vote"] != null)
                    {
                            <h4>Thanks for your feedback!</h4>
                    }
                }
                <br/>
                <br/>
                <br/>
                <br/>
            </div>
            i++;
        }
    
</div>