PhotoCritic/Controllers/PhotosController.cs
using Microsoft.AspNet.Identity;
using PhotoCritic.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
//using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
//using System.Web.UI.DataVisualization.Charting;

namespace PhotoCritic.Controllers
{
    public class PhotosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Photos
        public ActionResult Index(string categorySelectionForMe)
        {
            var userResult = User.Identity.GetUserId();
            var categories = db.Categories.Select(x => x.Name);
            ViewBag.categorySelectionForMe = new SelectList(categories);

            if (!string.IsNullOrEmpty(categorySelectionForMe))
            {
                var photosInCategory = db.Photos.Include(x => x.Category).Where(x => x.Category.Name.Contains(categorySelectionForMe) && userResult == x.ApplicationId).OrderByDescending(x => x.WhenCreated).ToList();
                return View(photosInCategory);
            }

            var myPhotos = db.Photos.Include(x => x.Category).Where(x => userResult == x.ApplicationId).OrderByDescending(x => x.WhenCreated).ToList();
            return View(myPhotos);
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var categories = db.Categories.ToList();
            Photo photo = db.Photos.Find(id);
            {
                photo.Categories = categories;
            };
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            var categories = db.Categories.ToList();

            Photo photo = new Photo()
            {
                Categories = categories
            };
            return View(photo);
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ApplicationId,ImageName,ImagePath,CategoryId,Hidden,CommentsEnabled,TotalLikes,TotalDislikes,ImageFile,WhenCreated,TotalInteractions,Compare")] Photo photo)
        {
            photo.ApplicationId = User.Identity.GetUserId();

            string fileName = Path.GetFileNameWithoutExtension(photo.ImageFile.FileName);
            string extension = Path.GetExtension(photo.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            photo.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            photo.ImageFile.SaveAs(fileName);

            db.Photos.Add(photo);
            db.SaveChanges();
            ModelState.Clear();
            return RedirectToAction("Index");
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var categories = db.Categories.ToList();
            Photo photo = db.Photos.Find(id);
            {
                photo.Categories = categories;
            };
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ApplicationId,ImageName,ImagePath,CategoryId,Hidden,CommentsEnabled,TotalLikes,TotalDislikes,ImageFile,WhenCreated,TotalInteractions,Compare")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = db.Photos.Find(id);
            db.Photos.Remove(photo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Likes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Photo photo = db.Photos.Find(id);

            return View(photo);
        }

        public ActionResult GetAgeChartDataLike(int id)
        {
            List<OpinionatedIndividual> ListOfLikers = new List<OpinionatedIndividual>();
            var gettingOpinionatedIndividualId = db.OpinionatedIndividualPhotos.Where(x => x.PhotoId == id && x.LikeDislike == true).Select(x => x.OpinionatedIndividualId).ToList();
            foreach (var OpId in gettingOpinionatedIndividualId)
            {
                var gettingPerson = db.OpinionatedIndividuals.Include(x => x.Age).Where(x => x.Id == OpId).FirstOrDefault();
                ListOfLikers.Add(gettingPerson);
            }

            var keyCountPair = ListOfLikers.ToList().GroupBy(x => x.Age).Select(x => new { x.Key, Count = x.Count() }); 
            var ageKeys = keyCountPair.Select(x => x.Key.Name).ToArray(); 
            var ageCounts = keyCountPair.Select(x => x.Count).ToArray(); 
            TempData["ageKeyData"] = ageKeys;
            TempData["ageCountData"] = ageCounts;

            return null;
        }

        public ActionResult GetSexChartDataLike(int id)
        {
            List<OpinionatedIndividual> ListOfLikers = new List<OpinionatedIndividual>();
            var gettingOpinionatedIndividualId = db.OpinionatedIndividualPhotos.Where(x => x.PhotoId == id && x.LikeDislike == true).Select(x => x.OpinionatedIndividualId).ToList();
            foreach (var OpId in gettingOpinionatedIndividualId)
            {
                var gettingPerson = db.OpinionatedIndividuals.Include(x => x.Sex).Where(x => x.Id == OpId).FirstOrDefault();
                ListOfLikers.Add(gettingPerson);
            }

            var keyCountPair = ListOfLikers.ToList().GroupBy(x => x.Sex).Select(x => new { x.Key, Count = x.Count() });
            var sexKeys = keyCountPair.Select(x => x.Key.Name).ToArray();
            var sexCounts = keyCountPair.Select(x => x.Count).ToArray();
            TempData["sexKeyData"] = sexKeys;
            TempData["sexCountData"] = sexCounts;

            return null;
        }

        public ActionResult GetRaceChartDataLike(int id)
        {
            List<OpinionatedIndividual> ListOfLikers = new List<OpinionatedIndividual>();
            var gettingOpinionatedIndividualId = db.OpinionatedIndividualPhotos.Where(x => x.PhotoId == id && x.LikeDislike == true).Select(x => x.OpinionatedIndividualId).ToList();
            foreach (var OpId in gettingOpinionatedIndividualId)
            {
                var gettingPerson = db.OpinionatedIndividuals.Include(x => x.Race).Where(x => x.Id == OpId).FirstOrDefault();
                ListOfLikers.Add(gettingPerson);
            }

            var keyCountPair = ListOfLikers.ToList().GroupBy(x => x.Race).Select(x => new { x.Key, Count = x.Count() });
            var raceKeys = keyCountPair.Select(x => x.Key.Name).ToArray();
            var raceCounts = keyCountPair.Select(x => x.Count).ToArray();
            TempData["raceKeyData"] = raceKeys;
            TempData["raceCountData"] = raceCounts;

            return null;
        }

        public ActionResult GetLocationChartDataLike(int id)
        {
            List<OpinionatedIndividual> ListOfLikers = new List<OpinionatedIndividual>();
            var gettingOpinionatedIndividualId = db.OpinionatedIndividualPhotos.Where(x => x.PhotoId == id && x.LikeDislike == true).Select(x => x.OpinionatedIndividualId).ToList();
            foreach (var OpId in gettingOpinionatedIndividualId)
            {
                var gettingPerson = db.OpinionatedIndividuals.Include(x => x.Location).Where(x => x.Id == OpId).FirstOrDefault();
                ListOfLikers.Add(gettingPerson);
            }

            var keyCountPair = ListOfLikers.ToList().GroupBy(x => x.Location).Select(x => new { x.Key, Count = x.Count() });
            var locationKeys = keyCountPair.Select(x => x.Key.Name).ToArray();
            var locationCounts = keyCountPair.Select(x => x.Count).ToArray();
            TempData["locationKeyData"] = locationKeys;
            TempData["locationCountData"] = locationCounts;

            return null;
        }

        public ActionResult GetEducationChartDataLike(int id)
        {
            List<OpinionatedIndividual> ListOfLikers = new List<OpinionatedIndividual>();

PhotoCritic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PhotoCritic", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "OpinionatedIndividuals")</li>
                    <li>@Html.ActionLink("My Photos", "Index", "Photos")</li>
                    <li>@Html.ActionLink("Compare", "Compare", "Photos")</li>
                    <li>@Html.ActionLink("Upload", "Create", "Photos")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PhotoCritic</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PhotoCritic/Views/Shared/_Layout_User.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PhotoCritic", "Dashboard", "OpinionatedIndividuals", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Dashboard", "OpinionatedIndividuals")</li>
                    <li>@Html.ActionLink("Vote", "Index", "OpinionatedIndividuals")</li>
                    <li>@Html.ActionLink("My Photos", "Index", "Photos")</li>
                    <li>@Html.ActionLink("Upload", "Create", "Photos")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PhotoCritic</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>